# Generated by Django 4.2.4 on 2023-08-19 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgtemp', models.FloatField(blank=True, null=True)),
                ('avg_humidity', models.FloatField(blank=True, null=True)),
                ('rain_probability', models.FloatField(blank=True, null=True)),
                ('snow_probability', models.FloatField(blank=True, null=True)),
                ('activity', models.CharField(max_length=1000)),
                ('itinerary_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_manager.itinerary')),
            ],
        ),
    ]
