# Generated by Django 4.2.4 on 2023-08-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0002_itineraryentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryentries',
            name='activity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itineraryentries',
            name='itinerary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_entries', to='api_manager.itinerary'),
        ),
    ]
