# Generated by Django 4.2.4 on 2023-08-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0004_foodlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
