# Generated by Django 4.2.4 on 2023-08-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0005_alter_itinerary_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraryentries',
            old_name='itinerary_parent',
            new_name='itinerary',
        ),
    ]
