# Generated by Django 4.2.4 on 2023-08-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0007_remove_itinerary_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItineraryEntries',
            new_name='ItineraryEntry',
        ),
    ]
