# Generated by Django 4.2.4 on 2023-08-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0008_rename_itineraryentries_itineraryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
