# Generated by Django 4.2.4 on 2023-08-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_manager', '0009_itinerary_destination_alter_itinerary_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='itineraryentry',
            options={'ordering': ['date']},
        ),
    ]
